spring:
     datasource:
       url: jdbc:mysql://mysql:3306/client_db
       username: root
       password: 123456
       driver-class-name: com.mysql.cj.jdbc.Driver
     jpa:
       hibernate:
         ddl-auto: update
       show-sql: true
   server:
     port: 8087
   eureka:
     client:
       service-url:
         defaultZone: http://eureka-server:8761/eureka/
